-- MySQL Script generated by MySQL Workbench
-- Sun May 31 20:38:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecosystem_core
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecosystem_core
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecosystem_core` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecosystem_core` ;

-- -----------------------------------------------------
-- Table `ecosystem_core`.`tenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`tenant` (
  `id` CHAR(36) NOT NULL,
  `nome_conta` VARCHAR(100) NOT NULL,
  `plano` VARCHAR(30) NULL DEFAULT 'STANDARD',
  `status` VARCHAR(20) NULL DEFAULT 'ACTIVE',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_tenant_soft_delete` (`deleted_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`arquivo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `nome_original` VARCHAR(255) NOT NULL,
  `nome_armazenado` VARCHAR(255) NOT NULL,
  `extensao` VARCHAR(20) NOT NULL,
  `mime_type` VARCHAR(100) NOT NULL,
  `tamanho_bytes` BIGINT NOT NULL,
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `deleted_by` BIGINT NULL DEFAULT NULL,
  `deleted_at_index` VARCHAR(50) GENERATED ALWAYS AS (coalesce(cast(`deleted_at` as char charset utf8mb4),_utf8mb4'1')) STORED,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  UNIQUE INDEX `uq_arquivo_tenant_composto` (`id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `idx_arquivo_soft_delete` (`tenant_id` ASC, `deleted_at` ASC) VISIBLE,
  CONSTRAINT `fk_arquivo_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`arquivo_vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`arquivo_vinculo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` CHAR(36) NOT NULL,
  `arquivo_id` BIGINT NOT NULL,
  `tabela_referencia` VARCHAR(50) NOT NULL,
  `registro_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_arquivo_vinculo_unico` (`tenant_id` ASC, `arquivo_id` ASC, `tabela_referencia` ASC, `registro_id` ASC) VISIBLE,
  INDEX `fk_arq_vinc_arquivo` (`arquivo_id` ASC, `tenant_id` ASC) VISIBLE,
  CONSTRAINT `fk_arq_vinc_arquivo`
    FOREIGN KEY (`arquivo_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`arquivo` (`id` , `tenant_id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_arq_vinc_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`configuracao_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`configuracao_auditoria` (
  `tenant_id` CHAR(36) NOT NULL,
  `tabela_nome` VARCHAR(50) NOT NULL,
  `auditar` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`tenant_id`, `tabela_nome`),
  CONSTRAINT `configuracao_auditoria_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`empresa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `razao_social` VARCHAR(150) NOT NULL,
  `nome_fantasia` VARCHAR(150) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `inscricao_estadual` VARCHAR(20) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `logradouro` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `bairro` VARCHAR(50) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` CHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NULL DEFAULT NULL,
  `version` INT NULL DEFAULT '1',
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `deleted_by` BIGINT NULL DEFAULT NULL,
  `deleted_at_index` VARCHAR(50) GENERATED ALWAYS AS (coalesce(cast(`deleted_at` as char charset utf8mb4),_utf8mb4'1')) STORED,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  UNIQUE INDEX `uq_empresa_tenant_composto` (`id` ASC, `tenant_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_tenant_cnpj` (`tenant_id` ASC, `cnpj` ASC, `deleted_at_index` ASC) VISIBLE,
  INDEX `idx_empresa_tenant_fk` (`tenant_id` ASC, `id` ASC) VISIBLE,
  INDEX `idx_empresa_soft_delete` (`tenant_id` ASC, `deleted_at` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`pessoa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `nome_razao` VARCHAR(150) NOT NULL,
  `apelido_fantasia` VARCHAR(150) NULL DEFAULT NULL,
  `cpf_cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `version` INT NULL DEFAULT '1',
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `deleted_by` BIGINT NULL DEFAULT NULL,
  `deleted_at_index` VARCHAR(50) GENERATED ALWAYS AS (coalesce(cast(`deleted_at` as char charset utf8mb4),_utf8mb4'1')) STORED,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  UNIQUE INDEX `uq_pessoa_tenant_composto` (`id` ASC, `tenant_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_tenant_cpf_cnpj` (`tenant_id` ASC, `cpf_cnpj` ASC, `deleted_at_index` ASC) VISIBLE,
  INDEX `idx_pessoa_soft_delete` (`tenant_id` ASC, `deleted_at` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `pessoa_id` BIGINT NOT NULL,
  `empresa_padrao_id` BIGINT NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `mac_address_autorizado` VARCHAR(17) NULL DEFAULT NULL,
  `tentativas_login` INT NULL DEFAULT '0',
  `bloqueado_ate` DATETIME NULL DEFAULT NULL,
  `ultimo_acesso` DATETIME NULL DEFAULT NULL,
  `version` INT NULL DEFAULT '1',
  `status` VARCHAR(20) NULL DEFAULT 'ACTIVE',
  `consentimento_dados` TINYINT(1) NULL DEFAULT '0',
  `termo_aceito_em` TIMESTAMP NULL DEFAULT NULL,
  `versao_termo` VARCHAR(10) NULL DEFAULT NULL,
  `anonimizado_em` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `deleted_by` BIGINT NULL DEFAULT NULL,
  `deleted_at_index` VARCHAR(50) GENERATED ALWAYS AS (coalesce(cast(`deleted_at` as char charset utf8mb4),_utf8mb4'1')) STORED,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  UNIQUE INDEX `uq_usuario_tenant_composto` (`id` ASC, `tenant_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_tenant_email` (`tenant_id` ASC, `email` ASC, `deleted_at_index` ASC) VISIBLE,
  INDEX `fk_usuario_pessoa` (`pessoa_id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `fk_usuario_empresa_padrao` (`empresa_padrao_id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `idx_usuario_login` (`tenant_id` ASC, `email` ASC, `status` ASC) VISIBLE,
  INDEX `idx_usuario_soft_delete` (`tenant_id` ASC, `deleted_at` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa_padrao`
    FOREIGN KEY (`empresa_padrao_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`empresa` (`id` , `tenant_id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_usuario_pessoa`
    FOREIGN KEY (`pessoa_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`pessoa` (`id` , `tenant_id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_usuario_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`dispositivo_confiavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`dispositivo_confiavel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `dispositivo_token` VARCHAR(64) NOT NULL,
  `nome_dispositivo` VARCHAR(100) NOT NULL,
  `ultimo_acesso_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `valido_ate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dispositivo_token` (`dispositivo_token` ASC) VISIBLE,
  INDEX `fk_disp_conf_usuario` (`usuario_id` ASC, `tenant_id` ASC) VISIBLE,
  CONSTRAINT `fk_disp_conf_usuario`
    FOREIGN KEY (`usuario_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`usuario` (`id` , `tenant_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`perfil` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `chave_identificadora` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  `deleted_by` BIGINT NULL DEFAULT NULL,
  `deleted_at_index` VARCHAR(50) GENERATED ALWAYS AS (coalesce(cast(`deleted_at` as char charset utf8mb4),_utf8mb4'1')) STORED,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  UNIQUE INDEX `uq_perfil_tenant_composto` (`id` ASC, `tenant_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_tenant_perfil_chave` (`tenant_id` ASC, `chave_identificadora` ASC, `deleted_at_index` ASC) VISIBLE,
  INDEX `idx_perfil_tenant_fk` (`tenant_id` ASC, `id` ASC) VISIBLE,
  INDEX `idx_perfil_soft_delete` (`tenant_id` ASC, `deleted_at` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`empresa_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`empresa_usuario` (
  `tenant_id` CHAR(36) NOT NULL,
  `empresa_id` BIGINT NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  `perfil_id` BIGINT NOT NULL,
  PRIMARY KEY (`tenant_id`, `empresa_id`, `usuario_id`),
  INDEX `fk_emp_usr_empresa` (`empresa_id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `fk_emp_usr_usuario` (`usuario_id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `fk_emp_usr_perfil` (`perfil_id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `idx_emp_usr_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_emp_usr_empresa` (`empresa_id` ASC) VISIBLE,
  INDEX `idx_emp_usr_perfil` (`perfil_id` ASC) VISIBLE,
  CONSTRAINT `fk_emp_usr_empresa`
    FOREIGN KEY (`empresa_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`empresa` (`id` , `tenant_id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_emp_usr_perfil`
    FOREIGN KEY (`perfil_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`perfil` (`id` , `tenant_id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_emp_usr_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_emp_usr_usuario`
    FOREIGN KEY (`usuario_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`usuario` (`id` , `tenant_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`job_execucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`job_execucao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tipo_job` VARCHAR(50) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `inicio` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fim` TIMESTAMP NULL DEFAULT NULL,
  `erro_mensagem` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_job_status` (`status` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`sessao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`sessao_usuario` (
  `id` CHAR(64) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  `empresa_ativa_id` BIGINT NULL DEFAULT NULL,
  `refresh_token` CHAR(64) NULL DEFAULT NULL,
  `refresh_expira_em` TIMESTAMP NULL DEFAULT NULL,
  `ip_origem` VARCHAR(45) NULL DEFAULT NULL,
  `dispositivo_info` VARCHAR(255) NULL DEFAULT NULL,
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `expira_em` TIMESTAMP NOT NULL,
  `revogado_em` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `refresh_token` (`refresh_token` ASC) VISIBLE,
  INDEX `fk_sessao_tenant` (`tenant_id` ASC) VISIBLE,
  INDEX `fk_sessao_usuario_composta` (`usuario_id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `fk_sessao_empresa_simples` (`empresa_ativa_id` ASC) VISIBLE,
  INDEX `idx_sessao_usuario` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_sessao_expira` (`expira_em` ASC) VISIBLE,
  INDEX `idx_sessao_refresh` (`refresh_token` ASC) VISIBLE,
  INDEX `idx_sessao_ativa` (`usuario_id` ASC, `revogado_em` ASC, `expira_em` ASC) VISIBLE,
  CONSTRAINT `fk_sessao_empresa_simples`
    FOREIGN KEY (`empresa_ativa_id`)
    REFERENCES `ecosystem_core`.`empresa` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_sessao_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_sessao_usuario_composta`
    FOREIGN KEY (`usuario_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`usuario` (`id` , `tenant_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`log_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`log_auditoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` CHAR(36) NOT NULL,
  `usuario_id` BIGINT NULL DEFAULT NULL,
  `sessao_id` CHAR(64) NULL DEFAULT NULL,
  `contexto_modulo` VARCHAR(50) NOT NULL,
  `acao` VARCHAR(20) NOT NULL,
  `tabela_nome` VARCHAR(50) NOT NULL,
  `registro_id` VARCHAR(64) NOT NULL,
  `ip_origem` VARCHAR(45) NULL DEFAULT NULL,
  `dados_originais` JSON NULL DEFAULT NULL,
  `dados_novos` JSON NULL DEFAULT NULL,
  `data_hora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_log_sessao` (`sessao_id` ASC) VISIBLE,
  INDEX `idx_log_usuario_id` (`usuario_id` ASC) VISIBLE,
  INDEX `idx_log_periodo` (`data_hora` ASC) VISIBLE,
  INDEX `idx_log_tenant_tabela_registro` (`tenant_id` ASC, `tabela_nome` ASC, `registro_id` ASC) VISIBLE,
  CONSTRAINT `fk_log_sessao`
    FOREIGN KEY (`sessao_id`)
    REFERENCES `ecosystem_core`.`sessao_usuario` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_log_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`modulo_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`modulo_sistema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `icone` VARCHAR(50) NULL DEFAULT NULL,
  `ordem` INT NULL DEFAULT '0',
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  UNIQUE INDEX `nome` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`menu_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`menu_sistema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `modulo_id` BIGINT NOT NULL,
  `menu_pai_id` BIGINT NULL DEFAULT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `acao_comando` VARCHAR(255) NULL DEFAULT NULL,
  `ordem` INT NULL DEFAULT '0',
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  INDEX `modulo_id` (`modulo_id` ASC) VISIBLE,
  INDEX `menu_pai_id` (`menu_pai_id` ASC) VISIBLE,
  CONSTRAINT `menu_sistema_ibfk_1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `ecosystem_core`.`modulo_sistema` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `menu_sistema_ibfk_2`
    FOREIGN KEY (`menu_pai_id`)
    REFERENCES `ecosystem_core`.`menu_sistema` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`notificacao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  `tipo` VARCHAR(30) NULL DEFAULT 'INFO',
  `titulo` VARCHAR(100) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `acao_url` VARCHAR(255) NULL DEFAULT NULL,
  `lida` TINYINT(1) NULL DEFAULT '0',
  `data_leitura` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  INDEX `fk_notificacao_tenant` (`tenant_id` ASC) VISIBLE,
  INDEX `fk_notificacao_usuario` (`usuario_id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `idx_notificacao_feed` (`usuario_id` ASC, `lida` ASC, `created_at` ASC) VISIBLE,
  INDEX `idx_notificacao_usuario_data` (`usuario_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_notificacao_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `fk_notificacao_usuario`
    FOREIGN KEY (`usuario_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`usuario` (`id` , `tenant_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`outbox_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`outbox_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` CHAR(36) NOT NULL,
  `evento_tipo` VARCHAR(100) NOT NULL,
  `payload` JSON NOT NULL,
  `processado` TINYINT(1) NULL DEFAULT '0',
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_outbox_tenant` (`tenant_id` ASC) VISIBLE,
  INDEX `idx_outbox_processado` (`processado` ASC, `criado_em` ASC) VISIBLE,
  CONSTRAINT `fk_outbox_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`permissao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid_publico` CHAR(36) NOT NULL,
  `tenant_id` CHAR(36) NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  `modulo` VARCHAR(50) NOT NULL,
  `acao` VARCHAR(50) NOT NULL,
  `chave_composta` VARCHAR(101) GENERATED ALWAYS AS (concat(`modulo`,_utf8mb4':',`acao`)) STORED,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `version` INT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_publico` (`uuid_publico` ASC) VISIBLE,
  UNIQUE INDEX `uq_permissao_tenant_chave` (`tenant_id` ASC, `chave_composta` ASC) VISIBLE,
  CONSTRAINT `fk_permissao_tenant`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`perfil_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`perfil_permissao` (
  `perfil_id` BIGINT NOT NULL,
  `permissao_id` BIGINT NOT NULL,
  PRIMARY KEY (`perfil_id`, `permissao_id`),
  INDEX `idx_perf_perm_perm` (`permissao_id` ASC) VISIBLE,
  CONSTRAINT `perfil_permissao_ibfk_1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `ecosystem_core`.`perfil` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `perfil_permissao_ibfk_2`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `ecosystem_core`.`permissao` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`permissao_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`permissao_menu` (
  `permissao_id` BIGINT NOT NULL,
  `menu_sistema_id` BIGINT NOT NULL,
  PRIMARY KEY (`permissao_id`, `menu_sistema_id`),
  INDEX `menu_sistema_id` (`menu_sistema_id` ASC) VISIBLE,
  CONSTRAINT `permissao_menu_ibfk_1`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `ecosystem_core`.`permissao` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `permissao_menu_ibfk_2`
    FOREIGN KEY (`menu_sistema_id`)
    REFERENCES `ecosystem_core`.`menu_sistema` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`schema_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`schema_version` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `versao` VARCHAR(20) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `executado_por` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `versao` (`versao` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`sistema_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`sistema_config` (
  `chave` VARCHAR(100) NOT NULL,
  `valor_config` JSON NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`chave`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`tenant_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`tenant_config` (
  `tenant_id` CHAR(36) NOT NULL,
  `timezone` VARCHAR(50) NULL DEFAULT 'UTC',
  `moeda` VARCHAR(10) NULL DEFAULT 'BRL',
  `idioma` VARCHAR(10) NULL DEFAULT 'pt-BR',
  `config_smtp` JSON NULL DEFAULT NULL,
  `limite_usuarios` INT NULL DEFAULT '5',
  `customizacao_visual` JSON NULL DEFAULT NULL,
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`tenant_id`),
  CONSTRAINT `tenant_config_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`tenant_feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`tenant_feature` (
  `tenant_id` CHAR(36) NOT NULL,
  `feature_chave` VARCHAR(50) NOT NULL,
  `valor_config` JSON NULL DEFAULT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`tenant_id`, `feature_chave`),
  CONSTRAINT `tenant_feature_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`tenant_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`tenant_menu` (
  `tenant_id` CHAR(36) NOT NULL,
  `menu_id` BIGINT NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`tenant_id`, `menu_id`),
  INDEX `menu_id` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `tenant_menu_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `tenant_menu_ibfk_2`
    FOREIGN KEY (`menu_id`)
    REFERENCES `ecosystem_core`.`menu_sistema` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`tenant_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`tenant_modulo` (
  `tenant_id` CHAR(36) NOT NULL,
  `modulo_id` BIGINT NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '1',
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`tenant_id`, `modulo_id`),
  INDEX `modulo_id` (`modulo_id` ASC) VISIBLE,
  CONSTRAINT `tenant_modulo_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `tenant_modulo_ibfk_2`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `ecosystem_core`.`modulo_sistema` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`tenant_parametro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`tenant_parametro` (
  `tenant_id` CHAR(36) NOT NULL,
  `chave` VARCHAR(100) NOT NULL,
  `valor` TEXT NOT NULL,
  `version` INT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`tenant_id`, `chave`),
  CONSTRAINT `tenant_parametro_ibfk_1`
    FOREIGN KEY (`tenant_id`)
    REFERENCES `ecosystem_core`.`tenant` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`tentativa_login_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`tentativa_login_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id_detectado` CHAR(36) NULL DEFAULT NULL,
  `email_tentativa` VARCHAR(100) NOT NULL,
  `ip_origem` VARCHAR(45) NOT NULL,
  `dispositivo_info` VARCHAR(255) NULL DEFAULT NULL,
  `sucesso` TINYINT(1) NOT NULL,
  `motivo_falha` VARCHAR(50) NULL DEFAULT NULL,
  `data_hora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_seguranca_bruteforce` (`ip_origem` ASC, `sucesso` ASC, `data_hora` ASC) VISIBLE,
  INDEX `idx_seguranca_email` (`email_tentativa` ASC, `data_hora` ASC) VISIBLE,
  INDEX `idx_data_hora_retencao` (`data_hora` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`usuario_historico_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`usuario_historico_senha` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tenant_id` CHAR(36) NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  `senha_hash` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_hist_senha_usuario` (`usuario_id` ASC, `tenant_id` ASC) VISIBLE,
  INDEX `idx_hist_senha_usuario` (`tenant_id` ASC, `usuario_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `fk_hist_senha_usuario`
    FOREIGN KEY (`usuario_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`usuario` (`id` , `tenant_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`usuario_mfa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`usuario_mfa` (
  `usuario_id` BIGINT NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `tipo` VARCHAR(20) NULL DEFAULT 'TOTP',
  `mfa_secret` VARCHAR(128) NOT NULL,
  `ativo` TINYINT(1) NULL DEFAULT '0',
  `atualizado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_mfa_usuario_composta` (`usuario_id` ASC, `tenant_id` ASC) VISIBLE,
  CONSTRAINT `fk_mfa_usuario_composta`
    FOREIGN KEY (`usuario_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`usuario` (`id` , `tenant_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`usuario_permissao` (
  `usuario_id` BIGINT NOT NULL,
  `permissao_id` BIGINT NOT NULL,
  PRIMARY KEY (`usuario_id`, `permissao_id`),
  INDEX `idx_usr_perm_perm` (`permissao_id` ASC) VISIBLE,
  CONSTRAINT `usuario_permissao_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ecosystem_core`.`usuario` (`id`)
    ON DELETE RESTRICT,
  CONSTRAINT `usuario_permissao_ibfk_2`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `ecosystem_core`.`permissao` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecosystem_core`.`usuario_seguranca_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecosystem_core`.`usuario_seguranca_config` (
  `usuario_id` BIGINT NOT NULL,
  `tenant_id` CHAR(36) NOT NULL,
  `requer_nova_senha` TINYINT(1) NULL DEFAULT '0',
  `aceita_acesso_fora_empresa` TINYINT(1) NULL DEFAULT '1',
  `ip_estatico_obrigatorio` VARCHAR(45) NULL DEFAULT NULL,
  `permitir_multiplas_sessoes` TINYINT(1) NULL DEFAULT '0',
  `atualizado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_usr_seg_usuario` (`usuario_id` ASC, `tenant_id` ASC) VISIBLE,
  CONSTRAINT `fk_usr_seg_usuario`
    FOREIGN KEY (`usuario_id` , `tenant_id`)
    REFERENCES `ecosystem_core`.`usuario` (`id` , `tenant_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
